apiVersion: v1
kind: Service
metadata:
  name: k8s-cicd-demo-svc
spec:
  type: NodePort
  selector:
    app: k8s-cicd-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
